/* Generated by export.py - do not add secrets here */
window.EXPENSE_DATA = [
  {
    "id": 1,
    "date": "2026-06-28",
    "category": "groceries",
    "amount": 120.5,
    "note": "starter item",
    "type": "expense",
    "chat_id": 123456789,
    "created_at": "2026-06-28T23:28:27.243327"
  }
];

window.EXPENSE_CONFIG = {
  "currency": "₹",
  "monthlyBudget": 50000,
  "budgets": {
    "travel": 8000,
    "food": 12000,
    "groceries": 8000,
    "clothes": 5000,
    "rent": 15000,
    "bills": 4000,
    "luxuries": 5000,
    "investments": 6000,
    "health": 3000,
    "education": 3000,
    "other": 2000
  }
};
