import json
import os
from pathlib import Path

from db import ExpenseDB

CONFIG_FILE = Path(__file__).resolve().parent / "config.json"
OUTPUT_FILE = Path(__file__).resolve().parent / "data.js"
DB_FILE = os.getenv("DATABASE_URL", str(Path(__file__).resolve().parent / "expenses.db"))


def load_config() -> dict:
    with open(CONFIG_FILE, "r", encoding="utf-8") as handle:
        config = json.load(handle)
    safe_config = {
        "currency": config.get("currency", "₹"),
        "monthlyBudget": config.get("monthlyBudget", 0),
        "budgets": config.get("budgets", {}),
    }
    return safe_config


def export_data(db_path: str | Path = DB_FILE, output_path: str | Path = OUTPUT_FILE) -> None:
    db = ExpenseDB(str(db_path))
    data = db.all_rows()
    config = load_config()
    payload = [
        {
            "id": row["id"],
            "date": row["date"],
            "category": row["category"],
            "amount": row["amount"],
            "note": row["note"],
            "type": row["type"],
            "chat_id": row["chat_id"],
            "created_at": row["created_at"],
        }
        for row in data
    ]
    js = (
        "/* Generated by export.py - do not add secrets here */\n"
        + "window.EXPENSE_DATA = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + ";\n\n"
        + "window.EXPENSE_CONFIG = "
        + json.dumps(config, ensure_ascii=False, indent=2)
        + ";\n"
    )
    with open(output_path, "w", encoding="utf-8") as out_file:
        out_file.write(js)


if __name__ == "__main__":
    export_data()
